language: node_js
node_js:
  - "0.12"
  - "0.11"
after_success:
- ./node_modules/.bin/jscoverage lib lib-cov
- ./node_modules/.bin/mocha test/**.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js